//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavbarItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NavbarItem()
        {
            this.NavbarItems1 = new HashSet<NavbarItem>();
            this.Products = new HashSet<Product>();
            this.ProductNavbarLinks = new HashSet<ProductNavbarLink>();
        }
    
        public int ItemId { get; set; }
        public string ItemText { get; set; }
        public string ItemUrl { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<bool> ItemVisible { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int LayoutType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NavbarItem> NavbarItems1 { get; set; }
        public virtual NavbarItem NavbarItem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNavbarLink> ProductNavbarLinks { get; set; }
    }
}
