//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavbarItem
    {
        public int ItemId { get; set; }
        public string ItemText { get; set; }
        public string ItemUrl { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<bool> ItemVisible { get; set; }
    }
}
