//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRanx
    {
        public int RangeId { get; set; }
        public string RangeLabel { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public Nullable<int> RangeOrder { get; set; }
    }
}
