//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore_New.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCollection()
        {
            this.ProductCollectionItems = new HashSet<ProductCollectionItem>();
        }
    
        public int CollectionId { get; set; }
        public string Name { get; set; }
        public string Handle { get; set; }
        public bool IsPublished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCollectionItem> ProductCollectionItems { get; set; }
    }
}
